# Generated by Django 5.2.10 on 2026-06-03 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verify_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verify_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='approval_note',
            field=models.TextField(blank=True, help_text='Admin note shown to seller on rejection'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved — live'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Hawker', 'Hawker / Street vendor'), ('Retail shop', 'Retail shop owner'), ('Repair shop', 'Phone repair shop'), ('Online seller', 'Online seller (WhatsApp / social media)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='BuyerSellerRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('denied', 'Denied')], db_index=True, default='pending', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_relationships', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_relationships', to='accounts.sellerprofile')),
            ],
            options={
                'ordering': ['-requested_at'],
                'unique_together': {('buyer', 'seller')},
            },
        ),
    ]
