# Generated by Django 5.2.10 on 2026-07-27 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_email_verify_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this seller', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sellers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='submitted_for_review_at',
            field=models.DateTimeField(blank=True, help_text='When seller was submitted or resubmitted for review', null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='approval_note',
            field=models.TextField(blank=True, help_text='Admin note shown to seller on rejection or needs_info'),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved — live'), ('rejected', 'Rejected'), ('needs_info', 'Needs more information')], db_index=True, default='pending', max_length=12),
        ),
    ]
