# Generated by Django 5.2.10 on 2026-07-28 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sellerprofile_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerStoreFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_stores', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('buyer', 'seller')},
            },
        ),
    ]
