# Generated by Django 5.2.10 on 2026-08-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_phone_number_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='mpesa_paybill_account',
            field=models.CharField(blank=True, help_text='Account number/name buyers enter with the paybill', max_length=50),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='mpesa_paybill_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='mpesa_pochi_number',
            field=models.CharField(blank=True, help_text='Pochi la Biashara number', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='mpesa_send_money_number',
            field=models.CharField(blank=True, help_text='Phone number for a plain Send Money payment', max_length=20),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='mpesa_till_number',
            field=models.CharField(blank=True, help_text='Buy Goods & Services till number', max_length=20),
        ),
    ]
