# Generated by Django 5.2.10 on 2026-08-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_amount_paid_order_final_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_sourcing',
            field=models.BooleanField(default=False),
        ),
    ]
