# Generated by Django 5.2.10 on 2026-08-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderstatusevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flag_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
