# Generated by Django 5.2.10 on 2026-08-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_flag_reason_order_flagged_at_order_is_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('sourcing', 'Sourcing'), ('locked', 'Locked'), ('debt_active', 'Debt Active'), ('cleared', 'Cleared'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=20),
        ),
    ]
