# Generated by Django 5.2.10 on 2026-08-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
    ]
