# Generated by Django 5.2.10 on 2026-08-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_custom_name_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='not_found',
            field=models.BooleanField(default=False),
        ),
    ]
