# Generated by Django 5.2.10 on 2026-08-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_paymentclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentclaim',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
