# Generated by Django 5.2.10 on 2026-08-18 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_paymentclaim_resolved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', '-created_at'], name='orders_orde_seller__c9231f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', '-created_at'], name='orders_orde_buyer_i_67c51b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', 'status'], name='orders_orde_seller__c90b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='orders_orde_buyer_i_4389c9_idx'),
        ),
    ]
