# Generated by Django 5.2.10 on 2026-08-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_orders_orde_seller__c9231f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_debt_reminder_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
