# Generated by Django 5.2.17 on 2026-09-22 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_pushsubscription'),
        ('orders', '0015_cartdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_percent', models.DecimalField(decimal_places=3, default='0.500', max_digits=5)),
                ('round_to_kes', models.PositiveIntegerField(default=5)),
                ('min_fee_kes', models.DecimalField(decimal_places=2, default='10.00', max_digits=8)),
                ('max_fee_kes', models.DecimalField(decimal_places=2, default='250.00', max_digits=8)),
                ('free_orders_allowance', models.PositiveIntegerField(default=3)),
                ('buyer_rate_percent', models.DecimalField(decimal_places=3, default='0.000', max_digits=5)),
                ('buyer_round_to_kes', models.PositiveIntegerField(default=5)),
                ('buyer_min_fee_kes', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('buyer_max_fee_kes', models.DecimalField(decimal_places=2, default='0.00', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('waived_free', "Waived — one of the seller's free orders"), ('charged', 'Charged'), ('refunded', 'Refunded — order cancelled before payment')], db_index=True, max_length=12)),
                ('charged_at', models.DateTimeField(auto_now_add=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_fee', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('credit_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_orders_used', models.PositiveIntegerField(default=0)),
                ('debt_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to='accounts.sellerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Waiting for the customer'), ('success', 'Paid'), ('failed', 'Failed')], db_index=True, default='initiated', max_length=10)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.selleraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
