# Generated by Django 5.2.17 on 2026-09-26 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def opening_balances(apps, schema_editor):
    """
    Any account that already holds credit (or owes) before the ledger existed gets
    one opening-balance entry, so credit_kes still equals the sum of its entries.
    Skips accounts that have entries already, so it is safe to run twice.
    """
    SellerAccount = apps.get_model("billing", "SellerAccount")
    CreditEntry = apps.get_model("billing", "CreditEntry")
    for account in SellerAccount.objects.exclude(credit_kes=0).filter(entries__isnull=True):
        CreditEntry.objects.create(
            account=account, account_number=account.account_number, kind="adjustment",
            amount_kes=account.credit_kes, balance_after_kes=account.credit_kes,
            note="Opening balance when the ledger was introduced",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_fee_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, max_length=20)),
                ('kind', models.CharField(choices=[('fee_charged', 'Fee charged'), ('fee_refunded', 'Fee refunded'), ('top_up', 'Top-up'), ('adjustment', 'Adjustment by Nyakizu staff')], db_index=True, max_length=12)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after_kes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='billing.selleraccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='billing.orderfee')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='billing.payment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RunPython(opening_balances, migrations.RunPython.noop),
    ]
