# Generated by Django 5.2.10 on 2026-08-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_seed_phone_accessory_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('draft', 'Draft')], db_index=True, default='available', max_length=20),
        ),
    ]
